// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/grimwild": {
    params: {};
  };
  "/grimwild/chapter-1": {
    params: {};
  };
  "/grimwild/chapter-2": {
    params: {};
  };
  "/grimwild/chapter-3": {
    params: {};
  };
  "/grimwild/chapter-4": {
    params: {};
  };
  "/grimwild/chapter-5": {
    params: {};
  };
  "/grimwild/chapter-7": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/grimwild" | "/grimwild/chapter-1" | "/grimwild/chapter-2" | "/grimwild/chapter-3" | "/grimwild/chapter-4" | "/grimwild/chapter-5" | "/grimwild/chapter-7";
  };
  "./books/core/About.tsx": {
    id: "books/core/About";
    page: "/grimwild";
  };
  "./books/core/Chapter01.tsx": {
    id: "books/core/Chapter01";
    page: "/grimwild/chapter-1";
  };
  "./books/core/Chapter02.tsx": {
    id: "books/core/Chapter02";
    page: "/grimwild/chapter-2";
  };
  "./books/core/Chapter03.tsx": {
    id: "books/core/Chapter03";
    page: "/grimwild/chapter-3";
  };
  "./books/core/Chapter04.tsx": {
    id: "books/core/Chapter04";
    page: "/grimwild/chapter-4";
  };
  "./books/core/Chapter05.tsx": {
    id: "books/core/Chapter05";
    page: "/grimwild/chapter-5";
  };
  "./books/core/Chapter07.tsx": {
    id: "books/core/Chapter07";
    page: "/grimwild/chapter-7";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "books/core/About": typeof import("./src/./books/core/About.tsx");
  "books/core/Chapter01": typeof import("./src/./books/core/Chapter01.tsx");
  "books/core/Chapter02": typeof import("./src/./books/core/Chapter02.tsx");
  "books/core/Chapter03": typeof import("./src/./books/core/Chapter03.tsx");
  "books/core/Chapter04": typeof import("./src/./books/core/Chapter04.tsx");
  "books/core/Chapter05": typeof import("./src/./books/core/Chapter05.tsx");
  "books/core/Chapter07": typeof import("./src/./books/core/Chapter07.tsx");
};